### PR TITLE
Add support for multiple devices & topics

### PR DESCRIPTION
**Pull request by swaffoja**
I needed the ability to send messages to multiple devices (multicast messages). I also added support for conditional topics. Let me know what you think or if you would prefer to implement a different way.

https://firebase.google.com/docs/cloud-messaging/http-server-ref#send-downstream

### CODE REVIEW

**Comment by thomas2411** [comment]
This is a great solution I currently need. The only problem I see is the 1000 devices limit. It just goes with out of range. So we need to handle it by ourselves when adding recipients and paginate it. I wonder what would be the best solution. Enclose send action and paginate it there? I mean get first 1000 devices, send, wait for response, send another 1000 etc? But how to handle responses then. I don't have an experience in this kind of situations.

**Comment by swaffoja** [comment]
Pagination seems OK to me... but it depends on how many devices you are really sending to. If you are sending to say 3000 devices then sending and processing 3 separate messages seems reasonable. If you wanted to send to 100000 devices then I be more hesitant to send and process 100 separate messages.

Topics seem like the preferred way to send messages to many recipients. Is there a way that you can alter your workflow to use topics? Could you add all of your recipients to a topic, send the message, process response, delete the topic (if needed). `Client.php` has a method `addTopicSubscription` that allows you to bulk subscribe recipients.

**Comment by thomas2411** [comment]
Indeed topics would be a better solution. Thanks.

**Comment by XAOPT** [comment]
This branch should be merged. For sure )

**Pull request merged**
